Misaar/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Misaar.Models
{
    public class Contact 
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Display(Name = "Страна")]
        public string Country { get; set; }

        [Display(Name = "Город")]
        public string City { get; set; }

        [Display(Name = "Адрес")]
        public string Address { get; set; }

        [Display(Name = "Почтовый индекс")]
        public string PostIndex { get; set; }

        [Display(Name = "Электронная почта")]
        public string Email { get; set; }

        [Display(Name = "Адрес склада 1")]
        public string StorageAddr1 { get; set; }

        [Display(Name = "Адрес склада 2")]
        public string StorageAddr2 { get; set; }

        [Display(Name = "Адрес склада 3")]
        public string StorageAddr3 { get; set; }       

        public virtual ICollection<Phone> Phones { get; set; }
    }
}

Misaar/Models/ContactViewModel.cs
using System.Collections.Generic;

namespace Misaar.Models
{
    public class ContactViewModel
    {
        public IEnumerable<Contact> Contacts { get; set; }
        public IEnumerable<Phone> Phones { get; set; }
    }
}

Misaar/Areas/Admin/Controllers/ContactsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Misaar.Models;
using Misaar.Concrete;

namespace Misaar.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class ContactsController : Controller
    {
        UnitOfWork unitOfWork;
        public ContactsController()
        {
            unitOfWork = new UnitOfWork();
        }
        // GET: Contacts
        public async Task<ActionResult> Index()
        {
            return View(await unitOfWork.Contacts.GetAll());
        }

        // GET: Contacts/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = await unitOfWork.Contacts.Get(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // GET: Contacts/Create
        public ActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Country,City,Address,PostIndex,Email,StorageAddr1,StorageAddr2,StorageAddr3")] Contact contact)
        {
            contact.Phones = new List<Phone>();
            if (ModelState.IsValid)
            {               
                unitOfWork.Contacts.Create(contact);
                await unitOfWork.Save();
                return RedirectToAction("Index");
            }

            return View(contact);
        }

        // GET: Contacts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = await unitOfWork.Contacts.Get(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Edit/5
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Country,City,Address,PostIndex,Email,StorageAddr1,StorageAddr2,StorageAddr3")] Contact contact)
        {
            if (ModelState.IsValid)
            {                
                unitOfWork.Contacts.Update(contact);
                await unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        // GET: Contacts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = await unitOfWork.Contacts.Get(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {            
            unitOfWork.Contacts.Delete(id);
            await unitOfWork.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Misaar/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Misaar.Models;
using Misaar.Concrete;

namespace Misaar.Controllers
{
    public class ContactsController : Controller
    {
        UnitOfWork unitOfWork;
        public ContactsController()
        {
            unitOfWork = new UnitOfWork();
        }
        // GET: Contacts
        public async Task<ActionResult> Index()
        {
            return View(await unitOfWork.Contacts.GetAll());
        }

        // GET: Contacts/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = await unitOfWork.Contacts.Get(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // GET: Contacts/Create
        public ActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Country,City,Address,PostIndex,Email,StorageAddr1,StorageAddr2,StorageAddr3")] Contact contact)
        {
            contact.Phones = new List<Phone>();
            if (ModelState.IsValid)
            {               
                unitOfWork.Contacts.Create(contact);
                await unitOfWork.Save();
                return RedirectToAction("Index");
            }

            return View(contact);
        }

        // GET: Contacts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = await unitOfWork.Contacts.Get(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Edit/5
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Country,City,Address,PostIndex,Email,StorageAddr1,StorageAddr2,StorageAddr3")] Contact contact)
        {
            if (ModelState.IsValid)
            {                
                unitOfWork.Contacts.Update(contact);
                await unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        // GET: Contacts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = await unitOfWork.Contacts.Get(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {            
            unitOfWork.Contacts.Delete(id);
            await unitOfWork.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Misaar/Controllers/PhonesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Misaar.Models;
using Misaar.Concrete;

namespace Misaar.Controllers
{
    public class PhonesController : Controller
    {
        UnitOfWork unitOfWork;
        public PhonesController()
        {
            unitOfWork = new UnitOfWork();
        }

        // GET: Phones
        public async Task<ActionResult> Index()
        {
            return View(await unitOfWork.Phones.GetAll());
        }

        // GET: Phones/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phone phone = await unitOfWork.Phones.Get(id);
            if (phone == null)
            {
                return HttpNotFound();
            }
            return View(phone);
        }

        // GET: Phones/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Phones/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Number,Operator,HasViber,ContactId")] Phone phone)
        {
            if (ModelState.IsValid)
            {
                phone.ContactId = 1;
                unitOfWork.Phones.Create(phone);
                await unitOfWork.Save();
                return RedirectToAction("Index");
            }

            return View(phone);
        }

        // GET: Phones/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phone phone = await unitOfWork.Phones.Get(id);
            if (phone == null)
            {
                return HttpNotFound();
            }
            return View(phone);
        }

        // POST: Phones/Edit/5
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Number,Operator,HasViber,ContactId")] Phone phone)
        {
            if (ModelState.IsValid)
            {
                phone.ContactId = 1;
                unitOfWork.Phones.Update(phone);
                await unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(phone);
        }

        // GET: Phones/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phone phone = await unitOfWork.Phones.Get(id);
            if (phone == null)
            {
                return HttpNotFound();
            }
            return View(phone);
        }

        // POST: Phones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            unitOfWork.Phones.Delete(id);
            await unitOfWork.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Misaar/Areas/Admin/Views/Contacts/Create.cshtml
@model Misaar.Models.Contact

@{
    ViewBag.Title = "Создание контакта";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Создание контакта</h2>
<a href=@Url.Action("Index", "Phones")>
    <p class="btn btn-primary btn-text">
        Телефоны
    </p>
</a>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostIndex, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostIndex, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostIndex, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StorageAddr1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StorageAddr1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StorageAddr1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StorageAddr2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StorageAddr2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StorageAddr2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StorageAddr3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StorageAddr3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StorageAddr3, "", new { @class = "text-danger" })
            </div>
        </div>       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    <a href=@Url.Action("Index", "Contacts") class="btn btn-default">
        К списку
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Misaar/Areas/Admin/Views/Contacts/Delete.cshtml
@model Misaar.Models.Contact

@{
    ViewBag.Title = "Удаление контакта";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Удаление</h2>

<a href=@Url.Action("Index", "Phones")>
    <p class="btn btn-primary btn-text">
        Телефоны
    </p>
</a>

<h3>Удалять этот контакт крайне нежелательно.</h3>
<div>
    <h4>Контакт</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostIndex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostIndex)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StorageAddr1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StorageAddr1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StorageAddr2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StorageAddr2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StorageAddr3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StorageAddr3)
        </dd>       
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-danger" /> |
            <a href=@Url.Action("Index", "Contacts") class="btn btn-default">
                К списку
            </a>
        </div>
    }
</div>

Misaar/Areas/Admin/Views/Contacts/Details.cshtml
@model Misaar.Models.Contact

@{
    ViewBag.Title = "Детали";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Детали</h2>

<a href=@Url.Action("Index", "Phones")>
    <p class="btn btn-primary btn-text">
        Телефоны
    </p>
</a>

<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostIndex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostIndex)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StorageAddr1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StorageAddr1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StorageAddr2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StorageAddr2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StorageAddr3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StorageAddr3)
        </dd>        
    </dl>
</div>
<div>
<p class="btn btn-default">@Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }) </p>
    <a href=@Url.Action("Index", "Contacts") class="btn btn-default">
        К списку
    </a>
</div>

Misaar/Areas/Admin/Views/Contacts/Edit.cshtml
@model Misaar.Models.Contact

@{
    ViewBag.Title = "Редактирование контакта";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Редактирование</h2>

<a href=@Url.Action("Index", "Phones")>
    <p class="btn btn-primary btn-text">
        Телефоны
    </p>
</a>

@using (Html.BeginForm("Edit", "Contacts", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostIndex, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostIndex, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostIndex, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StorageAddr1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StorageAddr1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StorageAddr1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StorageAddr2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StorageAddr2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StorageAddr2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StorageAddr3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StorageAddr3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StorageAddr3, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить изменения" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    <a href=@Url.Action("Index", "Contacts") class="btn btn-default">
        К списку
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Misaar/Areas/Admin/Views/Contacts/Index.cshtml
@model IEnumerable<Misaar.Models.Contact>

@{
    ViewBag.Title = "Все контакты";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Контакты</h2>

<a href=@Url.Action("Index", "Phones")>
    <p class="btn btn-primary btn-text">
        Телефоны
    </p>
</a>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostIndex)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>       
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostIndex)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        
        <td class="group">
            <div class="btn btn-default">@Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) </div>
            <div class="btn btn-default">@Html.ActionLink("Детали", "Details", new { id = item.Id })</div>
            <div class="btn btn-default">@Html.ActionLink("Удалить", "Delete", new { id = item.Id })</div>
        </td>
    </tr>
}

</table>